name: Template Cleanup
on:
  create:

jobs:
  cleanup:
    # Only run on initial repo creation, not branch creation
    if: github.event.ref_type == 'repository'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Replace template variables
        run: |
          # Get repo name and current date
          REPO_NAME="${{ github.event.repository.name }}"
          CURRENT_DATE=$(date +%Y-%m-%d)

          # Replace variables in all files
          find . -type f -name "*.md" -o -name "*.py" -o -name "*.html" -o -name "*.js" | while read file; do
            sed -i "s/{{PROJECT_NAME}}/$REPO_NAME/g" "$file"
            sed -i "s/{{CREATION_DATE}}/$CURRENT_DATE/g" "$file"
            sed -i "s/{{TODAY}}/$CURRENT_DATE/g" "$file"
          done

      - name: Update README
        run: |
          # Update the template reference in README
          sed -i "s/YOUR_USERNAME/${{ github.repository_owner }}/g" README.md

      - name: Remove template files
        run: |
          rm -f .github/workflows/template-cleanup.yml
          rm -f .github/TEMPLATE_README.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "🎉 Initialize project from template"
          git push
